services:
  api:
    container_name: api-PicProfileMaker
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    # volumes:
    #   - .:/app
